baseURL = "https://gmarro.fr"
languageCode = "fr"
title = "Grégory MARRO"
theme = "hugo-initio"

[params]
    name = "Grégory MARRO"
    description = "Architecte IT Freelance"
    email = "contact@gmarro.fr"
    phone = ""
    address = "Nice, France"
    year = 2022
    avatar = "images/gmarro.png"
    avatarclass = "circle"
    background = ""
    banner = "images/background.webp"
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"
    author = "Sergey Pozhilov (GetTemplate.com)"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = true
    showClients = true
    showMenu = false

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = false

[[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[params.disqus]
    site = ""

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/grégory-marro-8a3a4089/"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/gmarro"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "gitlab"
	url = "https://gitlab.com/gmarro"
    icon = "fab fa-gitlab"
    footer = true
    sharethis = false
    network = ""